from __future__ import annotations

from models import InteractionCreate


SEED_INTERACTIONS = [
    {
        "prospect_name": "Maya Chen",
        "company": "Acme Logistics",
        "role_title": "VP Operations",
        "meeting_notes": "Maya wants better visibility into delayed shipments and fewer manual updates for enterprise customers.",
        "objections": "Pricing too high, Integration timeline",
        "competitor_mentioned": "ShipTrack Pro",
        "budget": "$85K annual budget, needs ROI proof",
        "timeline": "Pilot in Q3 if integration is under 45 days",
        "decision_makers": "Maya Chen, CFO Daniel Ortiz, Head of IT Priya Raman",
        "next_steps": "Send ROI model and integration plan by Friday",
    },
    {
        "prospect_name": "Maya Chen",
        "company": "Acme Logistics",
        "role_title": "VP Operations",
        "meeting_notes": "Operations team liked exception alerts but asked whether warehouse teams can keep existing scanning workflows.",
        "objections": "Integration timeline",
        "competitor_mentioned": "ShipTrack Pro",
        "budget": "Budget available if churn reduction is credible",
        "timeline": "Technical validation next month",
        "decision_makers": "Head of IT Priya Raman owns technical approval",
        "next_steps": "Schedule IT architecture review",
    },
    {
        "prospect_name": "Maya Chen",
        "company": "Acme Logistics",
        "role_title": "VP Operations",
        "meeting_notes": "CFO asked for a conservative payback case based on reducing customer escalation calls.",
        "objections": "Need CFO approval",
        "competitor_mentioned": "",
        "budget": "CFO wants payback under 9 months",
        "timeline": "CFO review before pilot approval",
        "decision_makers": "CFO Daniel Ortiz",
        "next_steps": "Send CFO-ready business case",
    },
    {
        "prospect_name": "Dr. Elena Morris",
        "company": "Northstar Health",
        "role_title": "Chief Medical Information Officer",
        "meeting_notes": "Northstar wants faster care-team handoffs and fewer missed follow-up tasks after discharge.",
        "objections": "Security concerns, Procurement delay",
        "competitor_mentioned": "CareFlow AI",
        "budget": "$120K innovation fund",
        "timeline": "Security review required before September pilot",
        "decision_makers": "Dr. Elena Morris, CISO Aaron Blake, Procurement lead Tara Singh",
        "next_steps": "Provide HIPAA and SOC 2 packet",
    },
    {
        "prospect_name": "Dr. Elena Morris",
        "company": "Northstar Health",
        "role_title": "Chief Medical Information Officer",
        "meeting_notes": "Clinical champions are excited about task continuity but CISO needs data retention details.",
        "objections": "Security concerns",
        "competitor_mentioned": "CareFlow AI",
        "budget": "Innovation fund approved pending CISO",
        "timeline": "Pilot window starts October 1",
        "decision_makers": "CISO Aaron Blake has veto power",
        "next_steps": "Book security deep dive with CISO",
    },
    {
        "prospect_name": "Dr. Elena Morris",
        "company": "Northstar Health",
        "role_title": "Chief Medical Information Officer",
        "meeting_notes": "Procurement warned vendor onboarding can take six weeks after security approval.",
        "objections": "Procurement delay",
        "competitor_mentioned": "",
        "budget": "Funds expire at calendar year end",
        "timeline": "Contract must start before December",
        "decision_makers": "Procurement lead Tara Singh",
        "next_steps": "Send vendor onboarding checklist",
    },
    {
        "prospect_name": "Jordan Patel",
        "company": "BrightBank",
        "role_title": "Director of Digital Banking",
        "meeting_notes": "BrightBank wants to reduce abandonment in small-business loan applications.",
        "objections": "Already using competitor, Security concerns",
        "competitor_mentioned": "Salesforce Financial Services Cloud",
        "budget": "$200K transformation budget",
        "timeline": "Decision in 60 days",
        "decision_makers": "Jordan Patel, CTO Nina Brooks, Risk Officer Samir Lee",
        "next_steps": "Share banking security architecture and migration examples",
    },
    {
        "prospect_name": "Jordan Patel",
        "company": "BrightBank",
        "role_title": "Director of Digital Banking",
        "meeting_notes": "Jordan said Salesforce is broad but not remembering branch conversations well enough.",
        "objections": "Already using competitor",
        "competitor_mentioned": "Salesforce Financial Services Cloud",
        "budget": "Can fund add-on if it improves conversion by 8 percent",
        "timeline": "Business case due next steering committee",
        "decision_makers": "Steering committee includes CTO and Risk",
        "next_steps": "Prepare conversion lift model",
    },
    {
        "prospect_name": "Jordan Patel",
        "company": "BrightBank",
        "role_title": "Director of Digital Banking",
        "meeting_notes": "Risk officer asked how customer conversation memories are governed and audited.",
        "objections": "Security concerns",
        "competitor_mentioned": "",
        "budget": "$200K still available",
        "timeline": "Risk approval before procurement",
        "decision_makers": "Risk Officer Samir Lee",
        "next_steps": "Send audit logging overview",
    },
    {
        "prospect_name": "Avery Stone",
        "company": "CloudNova",
        "role_title": "Chief Revenue Officer",
        "meeting_notes": "CloudNova wants account executives to stop losing context between expansion conversations.",
        "objections": "Pricing too high",
        "competitor_mentioned": "Gong",
        "budget": "$150K sales productivity budget",
        "timeline": "Could launch next quarter",
        "decision_makers": "Avery Stone, RevOps Director Mia Alvarez",
        "next_steps": "Send pricing options tied to AE ramp savings",
    },
    {
        "prospect_name": "Avery Stone",
        "company": "CloudNova",
        "role_title": "Chief Revenue Officer",
        "meeting_notes": "RevOps liked CRM sync but wants custom fields preserved.",
        "objections": "Integration timeline",
        "competitor_mentioned": "Gong",
        "budget": "Budget can flex with enterprise security package",
        "timeline": "RevOps validation within three weeks",
        "decision_makers": "Mia Alvarez owns RevOps sign-off",
        "next_steps": "Create CRM field mapping plan",
    },
    {
        "prospect_name": "Avery Stone",
        "company": "CloudNova",
        "role_title": "Chief Revenue Officer",
        "meeting_notes": "Avery asked for proof that reps will actually use the memory briefs before calls.",
        "objections": "Pricing too high",
        "competitor_mentioned": "",
        "budget": "$150K if adoption case is strong",
        "timeline": "Executive decision after RevOps validation",
        "decision_makers": "Avery Stone final signer",
        "next_steps": "Share adoption metrics from similar SaaS teams",
    },
    {
        "prospect_name": "Riya Kapoor",
        "company": "UrbanKart",
        "role_title": "Head of Marketplace Growth",
        "meeting_notes": "UrbanKart wants to personalize seller success outreach across thousands of merchants.",
        "objections": "Need CFO approval, Pricing too high",
        "competitor_mentioned": "Intercom",
        "budget": "$95K requested, CFO has approved $70K",
        "timeline": "Wants launch before holiday seller rush",
        "decision_makers": "Riya Kapoor, CFO Luis Mendoza, Seller Ops lead Hana Kim",
        "next_steps": "Send phased rollout proposal at $70K entry point",
    },
    {
        "prospect_name": "Riya Kapoor",
        "company": "UrbanKart",
        "role_title": "Head of Marketplace Growth",
        "meeting_notes": "Seller Ops wants reminders for promises made to top sellers and escalation history.",
        "objections": "Integration timeline",
        "competitor_mentioned": "Intercom",
        "budget": "$70K approved for phase one",
        "timeline": "Holiday readiness deadline is November 15",
        "decision_makers": "Hana Kim influences rollout scope",
        "next_steps": "Confirm two-week seller data import plan",
    },
    {
        "prospect_name": "Riya Kapoor",
        "company": "UrbanKart",
        "role_title": "Head of Marketplace Growth",
        "meeting_notes": "CFO wants evidence that the memory agent reduces churn among high-value sellers.",
        "objections": "Need CFO approval",
        "competitor_mentioned": "",
        "budget": "Phase one limited to $70K",
        "timeline": "CFO review next Wednesday",
        "decision_makers": "CFO Luis Mendoza",
        "next_steps": "Send churn prevention business case",
    },
]


def seed_payloads() -> list[InteractionCreate]:
    return [InteractionCreate(**item) for item in SEED_INTERACTIONS]
